### PR TITLE
fix sara-r5

### LINKED ISSUE #88: Build for sara-r5 fails
Building with feature, sara-r5 fails with quite a few import issues and ATAT issues see `cargo test --tests --features sara-r5`

### PR DESCRIPTION
**Pull request by tarfu**
Related to #88.

### CODE REVIEW

**Comment by tarfu** [comment]
It does compile for me now, with features sara-r5 and defmt-impl. I can't get it to run properly, but if it does need changes, I would open another PR.
But I can also collect all changes until it works here if that is better for you.

**Comment by tarfu** [comment]
Would also add https://github.com/BlackbirdHQ/atat/pull/171 to here

**Comment by tarfu** [comment]
Also will add this here https://github.com/BlackbirdHQ/ublox-sockets/pull/18 so that the versions are in sync

**Comment by tarfu** [comment]
@MathiasKoch I think this could be merged. It builds and seems to work. I would open another PR to bring it to live on embassy with only one executor and add some async functions for everything that writes stuff or has sleeps.

Currently, it sends plenty of commands to init AT, but then the ingress would only read them after it is too late.

**Comment by tarfu** [comment]
The async one could be a real big PR looking into it this evening. ...

**Comment by MathiasKoch** [comment]
Closes https://github.com/BlackbirdHQ/ublox-cellular-rs/issues/88

**Comment by MathiasKoch** [comment]
@tarfu Could you make the CI green :)

**Comment by tarfu** [comment]
@MathiasKoch Should be done.

**Pull request merged**
